[bars.status]
modules = ["volume", "battery", "mpris", "cpu", "tray"]
anchors = ["right"]
orientation = "vertical"

[modules.volume]
type = "volume"

[modules.battery]
type = "battery"

[modules.mpris]
type = "mpris"

[modules.cpu]
type = "cpu"

[modules.tray]
type = "tray"
